language: go
go:
- 1.x
script:
- make bootstrap
- GOOS=linux   GOARCH=386   go build -o helm-template-$TRAVIS_TAG-linux-i386
- GOOS=linux   GOARCH=amd64 go build -o helm-template-$TRAVIS_TAG-linux-amd64
- GOOS=windows GOARCH=386   go build -o helm-template-$TRAVIS_TAG-windows-i386.exe
- GOOS=windows GOARCH=amd64 go build -o helm-template-$TRAVIS_TAG-windows-amd64.exe
deploy:
  provider: releases
  api_key:
    secure: Uc0x3JExTRuOH+npSRE2FXspVNmJj4yn84mw2xc2tD6/YCiZ4t+SG/ZfZ/3gbud4MiRPdmc+J46XK14johExvV3Q4WE6TO8U4iCwR8u+bdiRJsQ5fIFmRDnfJG+YZ7lT1HDlHlOysibC9Hs+xdxh6rgHA84KmIeC3G7f2VkLMrH0HXNHUtuxS1SKyzSDD9gZzfgJ0RivLe1TLXFOMG5dL5NzUqf4JQzVd3N/xNg41dgAqDqkGjh3kbdq2L0/WOcWT88WxJBz60RDNQqYc4rYui58TS6VAJdBd5LRvsxLAnNnRIbCZQ26F49eRfL1y2FclhWxQ6A21EFfn0o5B70yxakGjN5i9T/6cAHCMTMQN/fOdnj0T2ga//4HlQFSFSIYLRzLheO7n7EcswBrJMrzZIgX8sFIUGNxXoumG6msJnDD9OMGaRUvn10XyFcCe30EMe7zJmZbJ07Jn4060IdyZ2UcdupBRaPZ1Dk6bjwLcOotCgaHlrVQVyoN/ee2oKzli2T7BBtCUBDlD9l5+iiwO/TiDGppf5C6G4MSnN4Y7Cln+rD4eyx4cQ1hknXHaRywgQb+zC59blN1ugiz66shNzybUfQTQSUNTu97JJIPSuNJ6XxaI0GlknhBr6TS2ixqssobNfH6KFAoh+2jUjZTxBV7YS+NkZOY4625W32g21s=
  file: helm-template-*
  skip_cleanup: true
  on:
    repo: n0madic/helm-template
    tags: true
